version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'tsdb'
       MYSQL_ROOT_PASSWORD: 'Testing.512'
  web:
    build: ./tsproj
    command: bash -c "python manage.py makemigrations subscription &&  python manage.py makemigrations tsusers && python manage.py migrate && python manage.py runserver 0.0.0.0:19093"
    volumes:
      - ./tsproj:/tsproj
    ports:
      - "19093:19093"
    depends_on:
      - db